version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    environment:
      - PORT:8080
    ports:
      - 127.0.0.1:8080:8080
